database_url: postgres://postgres:password@localhost:5432/bitcoin_indexer

start_height: 0
end_height: -1

batch_size: 5000
workers: 8

skip_spend_state: false
skip_receivers: false
skip_senders: false
skip_balances: false
skip_utxo_counts: false